language: node_js
node_js:
- stable
deploy:
  provider: npm
  email: n.kimura.cap@gmail.com
  api_key:
    secure: H0qaLW8WRHOmwAg0zvxq5ruqIK9diWWZ680TpWHSQXVYg0g/g57i40Z705k0K+zmSEF688sak7tsVe64fqWQiL0L6ZSrjrfC3F0SSwTrQKCfWKc3rMTHccXlARfWXxFespTNBVNzwqVbQZfq4TcmvRltcYtUMKAKWWxEodoHMY8uXpieZzS2fhGPrmfIdRSYEmgz5STVtNZJvjh/etKBZuszXUOfgVhDpKUTpJh3sc/+HP7uOvTQs351Q+2qYKHokEd6fgijIrcA0DV6MVMNM/lVVyWtYvUA+xLv1EyXEsO6UxOdn8h1DMNJ/bUBftPWAWzPbNdHEeLYtw7dh+epUDOIoNCgXFzzI/8DInLg23FdZHNncNW3vcJG1S6nSzOL/S/eSJO8z4bLvvSsCOJi5arRUyFYabMFc8jjCq+AQnxEKJtQZwDBHbauatE33n9S1uADJsTXVXrpE+8BZ62xJfcQqetbCd/DQ4O3UTY6fI6HKKZmfFfDTxabG1I7DMtHBfARGOTJ0zXtB8HgvCzXj3Y2/yr9lIkgu1Zm5PDfwI2tUXRSbQznUSWJZFxOuEtniQZtPikxIgeMbLAPXMAL5RVNdMMQqGnNqjb0NlpsCyUR/XB/pG6oSrl3OPi6IeoMSPmAH2NcHop3hH/EthBAdZoEx1HzCP208X6UyJSiCdE=
  on:
    tags: true
    repo: naokikimura/gulp-mocha-thin
